export enum Rol {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN_INSTITUCION = 'ADMIN_INSTITUCION',
  ADMIN_SEDE = 'ADMIN_SEDE',
  DOCENTE = 'DOCENTE',
  ESTUDIANTE = 'ESTUDIANTE',
  AUXILIAR_CONTABLE = 'AUXILIAR_CONTABLE'
}

